version: '3.7'

services:
    app:
        build: api
        restart: ${RESTART:-no}
        volumes: 
            - ./api:/app
        working_dir: /app
        ports: 
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        command: ['python','manage.py', 'runserver', '0.0.0.0:8000']