version: '3.7'

services:
    db:
        image: postgres:13
        restart: ${RESTART:-no}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123change}
        volumes: 
            - ./env/db:/var/lib/postgresql/data
        networks: 
            - app-newtwork

    app:
        build: api
        restart: ${RESTART:-no}
        depends_on: 
            - db
        links: 
            - db:db_postgres
        volumes: 
            - ./api:/app
        working_dir: /app
        ports: 
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        networks:
            - app-newtwork
            - nginx-gateway
    
        command: ${RUNSERVER:-/bin/bash}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123change}    
            VIRTUAL_HOST: bossabox-api.lfvilella.com
            VIRTUAL_HOST_ALIAS: bossabox-api.lfvilella.com,www.bossabox-api.lfvilella.com
            LETSENCRYPT_HOST: bossabox-api.lfvilella.com,www.bossabox-api.lfvilella.com
            LETSENCRYPT_EMAIL: vilella.luisfelipe+bossabox-api.lfvilella.com@gmail.com

networks:
    app-newtwork:
    nginx-gateway:
        external:
            name: nginx-gateway