version: '3.7'

services:
    db:
        image: postgres:13
        restart: ${RESTART:-no}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123change}
        volumes: 
            - ./env/db:/var/lib/postgresql/data

    app:
        build: api
        restart: ${RESTART:-no}
        depends_on: 
            - db
        links: 
            - db:db_postgres
        volumes: 
            - ./api:/app
        working_dir: /app
        ports: 
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        command: ['python','manage.py', 'runserver', '0.0.0.0:8000']
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123change}    
